logging:
  level:
    org.hibernate.SQL: debug # logger? ?????
    org.hibernate.type.descriptor.sql: trace # ???? ? ??
    springframework: # 추가!
      security: debug # 추가!
spring:
  jpa:
    show-sql: true # ????? ?????
    properties:
      hibernate:
        format_sql: true # SQL ???
        highlight_sql: true # ANSI ??? ?? ????
        use_sql_comments: true # SQL ??? /* */ ?? ??
auth:
  jwt:
    issuer: team.sparta.com
    secret: PO4c8z41Hia5gJG3oeuFJMRYBB4Ws4aZ
    accessTokenExpirationHour: 168